fixed bad characters in license text causing crash
License text contained backward double quotes instead
of plain double quotes.

  File "/opt/ibm/fdprpro/bin/fdpr_dl.py", line 6
SyntaxError: Non-ASCII character '\xe2' in file /opt/ibm/fdprpro/bin/fdpr_dl.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Signed-off-by: Paul A. Clarke <pc@us.ibm.com>